### ISSUE TITLE
Document MuSe/Love Spouse Protocol

### ISSUE THREAD

**Issue by denialtek** [buttplugio/docs.buttplug.io#2]
The toy is controlled by creating a BLE advertiser and setting specific manufacturer data.

**Properties:** Scannable, Connectable, Legacy
**Company ID:** 0xFFF0 (though other IDs seem to also work)
**Manufacturer Data:** 11 bytes in the format of 0x6DB643CE97FE427Cxxxxxx

Valid values for the last 3 bytes:
0xE5157D - stop all channels
0xE49C6C - set all channels to speed 1
0xE7075E - set all channels to speed 2
0xE68E4F - set all channels to speed 3

Only for use by toys with 2 channels:
0xD5964C- stop 1st channel
0xD41F5D - set 1st channel to speed 1
0xD7846F - set 1st channel to speed 2
0xD60D7E - set 1st channel to speed 3

0xA5113F - stop 2nd channel
0xA4982E - set 2nd channel to speed 1
0xA7031C - set 2nd channel to speed 2
0xA68A0D - set 2nd channel to speed 3

Some toys with both stroke and vibrate functionality have the vibrate on channel 1, and some have it on channel 2. There doesn't appear to be a way of knowing which functionality is on which channel.

The commands listed above correlate with the first 3 "modes" in the app, which are low/medium/high and are the only non-pattern modes.

Some commands trigger the toy to change patterns when the advertisement stops (ex. 0xE0B82A triggers a fast pulse pattern, but then a slower pulse pattern once you stop sending that data). To prevent the toy from thinking the advertisement data has stopped the advertisement interval needs to be at least 250ms.

**Comment by AndroSphinx** [comment]
Taking the above documentation, here's some ESP32 code that implements the above and is able to control these toys:

```
#include <Arduino.h>
#include <NimBLEDevice.h>

static uint16_t companyId = 0xFFF0;

#define MANUFACTURER_DATA_PREFIX 0x6D, 0xB6, 0x43, 0xCE, 0x97, 0xFE, 0x42, 0x7C

uint8_t manufacturerDataList[][11] = {
    // Stop all channels
    {MANUFACTURER_DATA_PREFIX, 0xE5, 0x15, 0x7D},
    // Set all channels to speed 1
    {MANUFACTURER_DATA_PREFIX, 0xE4, 0x9C, 0x6C},
    // Set all channels to speed 2
    {MANUFACTURER_DATA_PREFIX, 0xE7, 0x07, 0x5E},
    // Set all channels to speed 3
    {MANUFACTURER_DATA_PREFIX, 0xE6, 0x8E, 0x4F},
    // Stop 1st channel (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xD5, 0x96, 0x4C},
    // Set 1st channel to speed 1 (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xD4, 0x1F, 0x5D},
    // Set 1st channel to speed 2 (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xD7, 0x84, 0x6F},
    // Set 1st channel to speed 3 (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xD6, 0x0D, 0x7E},
    // Stop 2nd channel (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xA5, 0x11, 0x3F},
    // Set 2nd channel to speed 1 (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xA4, 0x98, 0x2E},
    // Set 2nd channel to speed 2 (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xA7, 0x03, 0x1C},
    // Set 2nd channel to speed 3 (only for toys with 2 channels)
    {MANUFACTURER_DATA_PREFIX, 0xA6, 0x8A, 0x0D},
};

const char *deviceName = "MuSE_Advertiser";

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE...");
  NimBLEDevice::init(deviceName);
}

void advertiseManufacturerData(uint8_t index) {
  NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();

  pAdvertising->stop();

  uint8_t *manufacturerData = manufacturerDataList[index];

  Serial.print("Advertising index: ");
  Serial.print(index);
  Serial.print(", data: ");
  for (int i = 0; i < 11; i++) {
    Serial.print(manufacturerDataList[index][i], HEX);
    if (i < 10) {
      Serial.print(", ");
    }
  }
  Serial.println();
  Serial.flush(); // Flush to ensure data is sent before delay

  pAdvertising->setManufacturerData(std::string((char *)&companyId, 2) + std::string((char *)manufacturerData, 11));

  // Set properties: scannable, connectable, and use legacy advertising
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x12);
  pAdvertising->setMinPreferred(0x02);

  // Start advertising
  pAdvertising->start();
}

void loop() {
  for (uint8_t i = 0; i < sizeof(manufacturerDataList) / sizeof(manufacturerDataList[0]); i++) {

    // set advertisement for 2 seconds
    for (uint8_t j = 0; j < 10; j++) {
      advertiseManufacturerData(i);
      delay(200);
    }
    // set stop devices for 1 second
    for (uint8_t k = 0; k < 5; k++) {
      advertiseManufacturerData(0);
      delay(200);
    }
  }
}
```

**Comment by jptrsn** [comment]
I have done some more sniffing, thanks to this info, and I was able to capture the values for both the **Classic Mode** as well as **Independent Mode (Mode 1)** (which I believe is in reference to motor 1). Modes 1, 2 and 3 of classic mode correspond with the previously-mentioned values. I do not have any dual-motor devices to test, but can capture the second motor advertisement values from the app if they prove useful to the development of xtoys.app. I think it may be viable to create an ESP32 gateway firmware that could replicate a buttplug.io compatible protocol over wifi or serial, and extend functionality.

Here are the values I've captured:
```
// Classic Mode
uint8_t manufacturerDataList[][11] = {
    // 0 Stop all channels 
    {MANUFACTURER_DATA_PREFIX, 0xE5, 0x15, 0x7D},
    // 1 Set all channels to speed 1 (Mode 1)
    {MANUFACTURER_DATA_PREFIX, 0xE4, 0x9C, 0x6C},
    // 2 Set all channels to speed 2 (Mode 2)
    {MANUFACTURER_DATA_PREFIX, 0xE7, 0x07, 0x5E},
    // 3 Set all channels to speed 3 (Mode 3)
    {MANUFACTURER_DATA_PREFIX, 0xE6, 0x8E, 0x4F},
    // 4 (Mode 4)
    {MANUFACTURER_DATA_PREFIX, 0xE1, 0x31, 0x3B},
    // 5 (Mode 5)
    {MANUFACTURER_DATA_PREFIX, 0xE0, 0xB8, 0x2A},
    // 6 (Mode 6)
    {MANUFACTURER_DATA_PREFIX, 0xE3, 0x23, 0x18},
    // 7 (Mode 7)
    {MANUFACTURER_DATA_PREFIX, 0xE2, 0xAA, 0x09},
    // 8 (Mode 8)
    {MANUFACTURER_DATA_PREFIX, 0xED, 0x5D, 0xF1},
    // 9 (Mode 9)
    {MANUFACTURER_DATA_PREFIX, 0xEC, 0xD4, 0xE0}
};
```

```
// Independent mode, vibe 1
uint8_t manufacturerDataList[][11] = {
    // 0 Stop all channels 
    {MANUFACTURER_DATA_PREFIX, 0xE5, 0x15, 0x7D},
    // 1 (Mode 1)
    {MANUFACTURER_DATA_PREFIX, 0xD4, 0x1F, 0x5D},
    // 2 (Mode 2)
    {MANUFACTURER_DATA_PREFIX, 0xD7, 0x84, 0x6F},
    // 3 (Mode 3)
    {MANUFACTURER_DATA_PREFIX, 0xD6, 0x0D, 0x7E},
    // 4 (Mode 4)
    {MANUFACTURER_DATA_PREFIX, 0xD1, 0xB2, 0x0A},
    // 5 (Mode 5)
    {MANUFACTURER_DATA_PREFIX, 0xD0, 0x3B, 0x1B},
    // 6 (Mode 6)
    {MANUFACTURER_DATA_PREFIX, 0xD3, 0xA0, 0x29},
    // 7 (Mode 7)
    {MANUFACTURER_DATA_PREFIX, 0xD2, 0x29, 0x38},
    // 8 (Mode 8)
    {MANUFACTURER_DATA_PREFIX, 0xDD, 0xDE, 0xC0},
    // 9 (Mode 9)
    {MANUFACTURER_DATA_PREFIX, 0xDC, 0x57, 0xD1}
};
```

**Comment by Paxy** [comment]
@jptrsn I just finished a project with that idea. https://github.com/Paxy/xtoys_LS_GW/

**Comment by IngeniousKink** [comment]
> create an ESP32 gateway firmware

I did just that: https://github.com/IngeniousKink/LVS-Gateway:

ESP32 firmware that poses as a Lovense toy and broadcasts the manufacturer data to MuSE/Love Spouse devices.

**Comment by arz321** [comment]
Hi, I'm researching the MuSe protocol in app Leten. And "decrypted" it.
In the process of research, I managed to download the entire database and there are more than 1000 toys in it.
And also i made an application to send packages
[https://github.com/arz321/MuSe-Protocol](https://github.com/arz321/MuSe-Protocol)

**Comment by denialtek** [comment]
For toy 8131 (a buttplug with an LED), the LED is controlled via the channel 2 commands, and each of the commands maps to a color:

0xA5113F - Off (it doesn't turn fully off, instead it's a dim blinking blue light)
0xA4982E - Sky Blue
0xA7031C - Deep Blue
0xA68A0D - Dark Green
0xA13579 - Light Purple
0xA0BC68 - Light Blue
0xA3275A - Orange
0xA2AE4B - Red
0xAD59B3 - Rose Red
0xACD0A2 - Light Green

**Comment by kidjuniper** [comment]
Hi! Did someone try to make an iOS app for such devices?

**Comment by qdot** [comment]
> Hi! Did someone try to make an iOS app for such devices?

Not possible. iOS does not expose ble peripheral capabilities.

**Comment by arz321** [comment]
I was able to decode the MuSe protocol using Ghidra and AI. And later I found out that this is the [Fastcon BLE](https://mooody.me/posts/2023-04/reverse-the-fastcon-ble-protocol-2/) implementation from BroadLink.
Example of use, we substitute the numbers from the barcode into the link
[https://lovespouse.zlmicro.com/index.php?g=App&m=Diyapp&a=getproductdetail&barcode=**8131**&userid=-1](https://lovespouse.zlmicro.com/index.php?g=App&m=Diyapp&a=getproductdetail&barcode=8131&userid=-1)
We take, from json, BroadcastPrefix "77 62 4d 53 45" and the stop command "30"
And we get 0x6D, 0xB6, 0x43, 0xCE, 0x97, 0xFE, 0x42, 0x7C, 0xE5, 0x15, 0x7D
p.s. Later I will do it for esp32


```java
//Java
public class Main {
    public static void main(String[] args) {
        byte[] broadcastPrefix = {0x77, 0x62, 0x4d, 0x53, 0x45};
        byte[] command = {0x30};

        int length = broadcastPrefix.length;
        int length2 = command.length;
        int length3 = broadcastPrefix.length + command.length + 0x05;

        byte[] data = new byte[length3];
    
        get_rf_payload(broadcastPrefix, length, command, length2, data);

        for (int i = 0; i < length3; i++) {
            System.out.print("0x");
            System.out.print(Integer.toHexString((int)data[i] & 0xff).toUpperCase());
            System.out.print(", ");
        } 
    }

    public static void get_rf_payload(byte[] bArr, int length, byte[] bArr2, int length2, byte[] bArr3) {

        byte[] ctx_25 = new byte[7];
        byte[] ctx_3F = new byte[7];

        whitening_init(0x25, ctx_25); //1100101
        whitening_init(0x3f, ctx_3F); //1111111

        int length_24 = 0x12 + length + length2;
        int length_26 = length_24 + 0x02;

        byte[] result_25 = new byte[length_26];
        byte[] result_3f = new byte[length_26];
        byte[] resultbuf = new byte[length_26];

        resultbuf[0x0f] = 0x71;//const buf[0x0f-0x11]
        resultbuf[0x10] = 0x0f;
        resultbuf[0x11] = 0x55;

        if (length > 0) {
            for (byte j = 0; j < length; j++) { //flip bArr[] and write to buf[0x12-0x16]
                resultbuf[0x12 + length - j - 0x01] = bArr[j];
            }
        }

        if (length2 > 0) {
            for (byte j = 0; j < length2; j++) { //flip bArr2[] and write to buf[0x17]
                resultbuf[length_24 - j - 0x01] = bArr2[j];
            }
        }

        for (byte i = 0; i < 0x03 + length; i++) { //invert_8 byte buf[0x0f-0x16]
            resultbuf[0x0f + i] = invert_8(resultbuf[0x0f + i]);
        }

        int crc16 = check_crc16(bArr, length, bArr2, length2); //write crc16 to buf[0x18-0x19]
        resultbuf[length_24] = (byte)crc16;
        resultbuf[length_24 + 1] = (byte)(crc16 >> 8);

        whitenging_encode(resultbuf, 0x2 + length + length2, ctx_3F, 0x12, result_3f);
        whitenging_encode(resultbuf, length_26, ctx_25, 0x00, result_25);

        for (byte i = 0; i < length_26; i++) { //XOR result_25[] and result_3f[]
            result_25[i] ^= result_3f[i];
        }

        System.arraycopy(result_25, 0x0f, bArr3, 0, 0x0b); //copy result_25[0x0f-0x19] to bArr3
    }

    public static void whitening_init(int val, byte[] ctx) {
        ctx[0] = 1;
        ctx[1] = (byte) ((val >> 5) & 1);
        ctx[2] = (byte) ((val >> 4) & 1);
        ctx[3] = (byte) ((val >> 3) & 1);
        ctx[4] = (byte) ((val >> 2) & 1);
        ctx[5] = (byte) ((val >> 1) & 1);
        ctx[6] = (byte) (val & 1);
    }

    public static int check_crc16(byte[] addr, int addrLength, byte[] data, int dataLength) {
        int crc = 0xffff;

        for (int i = addrLength - 1; i >= 0; i--) {
            crc ^= addr[i] << 8;
            for (int ii = 0; ii < 8; ii++) {
                if ((crc & 0x8000) != 0) {
                    crc = (crc << 1) ^ 0x1021;
                } else {
                    crc <<= 1;
                }
            }
        }

        for (int i = 0; i < dataLength; i++) {
            crc ^= invert_8(data[i]) << 8;
            for (int ii = 0; ii < 8; ii++) {
                if ((crc & 0x8000) != 0) {
                    crc = (crc << 1) ^ 0x1021;
                } else {
                    crc <<= 1;
                }
            }
        }
        crc = ~invert_16(crc) & 0xffff;
        return crc;
    }

    public static byte invert_8(byte value) {
        byte result = 0;
        for (byte i = 0; i < 8; i++) {
            result <<= 1;
            result |= (value & 1);
            value >>= 1;
        }
        return result;
    }

    public static int invert_16(int value) {
        int result = 0;
        for (int i = 0; i < 16; i++) {
            result <<= 1;
            result |= (value & 1);
            value >>= 1;
        }
        return result;
    }

    public static void whitenging_encode(byte[] data, int len, byte[] ctx, int offset, byte[] result) {
        System.arraycopy(data, 0, result, 0, len);
        for (int i = 0; i < len; i++) {
            int var6 = ctx[6];
            int var5 = ctx[5];
            int var4 = ctx[4];
            int var3 = ctx[3];
            int var52 = var5 ^ ctx[2];
            int var41 = var4 ^ ctx[1];
            int var63 = var6 ^ ctx[3];
            int var630 = var63 ^ ctx[0];

            ctx[0] = (byte)(var52 ^ var6);
            ctx[1] = (byte)var630;
            ctx[2] = (byte)var41;
            ctx[3] = (byte)var52;
            ctx[4] = (byte)(var52 ^ var3);
            ctx[5] = (byte)(var630 ^ var4);
            ctx[6] = (byte)(var41 ^ var5);

            int c = result[i + offset];
            result[i + offset] = (byte)(((c & 0x80) ^ ((var52 ^ var6) << 7)) +
                                        ((c & 0x40) ^ (var630 << 6)) +
                                        ((c & 0x20) ^ (var41 << 5)) +
                                        ((c & 0x10) ^ (var52 << 4)) +
                                        ((c & 0x08) ^ (var63 << 3)) +
                                        ((c & 0x04) ^ (var4 << 2)) +
                                        ((c & 0x02) ^ (var5 << 1)) +
                                        ((c & 0x01) ^ (var6)));
        }
    }
}
```

**Comment by arz321** [comment]
@denialtek I was able to control the toy from Windows with a little cheating. In a bluetooth packet a flag is transmitted that is 3 bytes long. in Windows it is not possible to transmit flags, but it seems that it is enough to compensate for the length of the packet by 3 bytes.
![origin](https://github.com/buttplugio/docs.buttplug.io/assets/143265231/86087339-e764-48a2-b9de-f4761299f1f8) ![windows](https://github.com/buttplugio/docs.buttplug.io/assets/143265231/e63d375e-c433-457a-85ef-957358585cde)
![image](https://github.com/buttplugio/docs.buttplug.io/assets/143265231/c3ec5492-d000-4fac-9ed8-96dc288f4329)

**Comment by Fi0nee** [comment]
Thank you all for the information. Here is my version of the ESP32 code for controlling modes via the web interface. Expanded the vibration levels and added all modes from the app + 1

What's new:
E5157D - Stop = E50000

f4619d - low 1 = f40000
f71c34 - low 2 = f70000
f6b6dc - low 3 = f60000
f1fb9d - low 4 = f10000
f3d9a5 - low 5 = f30000
E7075E - Medium = E70000
E6894F - Hight = E60000

E122B4 - Mode 4 = E10000
d00060 - Mode 5 = D00000
D31FA7 - Mode 6 = D30000
E2297B - Mode 7 = e20000
ED7076 - Mode 8 = ed0000
DC0A82 - Mode 9 = DC0000
E9B9C5 - mode 10 = e90000
```
#include <Arduino.h>
#include <NimBLEDevice.h>
#include <WiFi.h>
#include <WebServer.h>

// WiFi Credentials
const char *ssid = "SSID";
const char *password = "password";

// Web Server Port
const int webPort = 80;

// Web Server Object
WebServer server(webPort);

static uint16_t companyId = 0xFFF0;

#define MANUFACTURER_DATA_PREFIX 0x6D, 0xB6, 0x43, 0xCE, 0x97, 0xFE, 0x42, 0x7C

// Updated list of manufacturer data options with both speed and vibration modes
uint8_t manufacturerDataList[][11] = {
    {MANUFACTURER_DATA_PREFIX, 0xE5, 0x00, 0x00}, // Off (E50000)
    {MANUFACTURER_DATA_PREFIX, 0xF4, 0x00, 0x00}, // Mode 1 (F40000)
    {MANUFACTURER_DATA_PREFIX, 0xF7, 0x00, 0x00}, // Mode 2 (F70000)
    {MANUFACTURER_DATA_PREFIX, 0xF6, 0x00, 0x00}, // Mode 3 (F60000)
    {MANUFACTURER_DATA_PREFIX, 0xF1, 0x00, 0x00}, // Mode 4 (F10000)
    {MANUFACTURER_DATA_PREFIX, 0xF3, 0x00, 0x00}, // Mode 5 (F30000)
    {MANUFACTURER_DATA_PREFIX, 0xE7, 0x00, 0x00}, // Mode 6 (E70000)
    {MANUFACTURER_DATA_PREFIX, 0xE6, 0x00, 0x00}, // Mode 7 (E60000)
    {MANUFACTURER_DATA_PREFIX, 0xE1, 0x00, 0x00}, // Vibration 1 (E10000)
    {MANUFACTURER_DATA_PREFIX, 0xD0, 0x00, 0x00}, // Vibration 2 (D00000)
    {MANUFACTURER_DATA_PREFIX, 0xD3, 0x00, 0x00}, // Vibration 3 (D30000)
    {MANUFACTURER_DATA_PREFIX, 0xE2, 0x00, 0x00}, // Vibration 4 (E20000)
    {MANUFACTURER_DATA_PREFIX, 0xED, 0x00, 0x00}, // Vibration 5 (ED0000)
    {MANUFACTURER_DATA_PREFIX, 0xDC, 0x00, 0x00}, // Vibration 6 (DC0000)
    {MANUFACTURER_DATA_PREFIX, 0xE9, 0x00, 0x00}  // Vibration 7 (E90000)
};

const char *deviceName = "MuSE_Advertiser";

volatile uint8_t currentManufacturerDataIndex = 0;
volatile bool modeChanged = false;

void advertiseManufacturerData(uint8_t index) {
  NimBLEAdvertising *pAdvertising = NimBLEDevice::getAdvertising();
  pAdvertising->stop();
  uint8_t *manufacturerData = manufacturerDataList[index];
  pAdvertising->setManufacturerData(std::string((char *)&companyId, 2) + std::string((char *)manufacturerData, 11));
  pAdvertising->setScanResponse(true);
  pAdvertising->setMaxPreferred(0x12);
  pAdvertising->setMinPreferred(0x02);
  pAdvertising->start();
}

void connectWiFi() {
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
  }
}

void handleRoot() {
  String html = "<!DOCTYPE html>";
  html += "<html lang=\"ru\">";
  html += "<head>";
  html += "<meta charset=\"UTF-8\">";
  html += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
  html += "<style>";
  html += "body { font-family: Arial, sans-serif; text-align: center; margin: 0; padding: 0; background-color: #f4f4f4; }";
  html += ".container { display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; }";
  html += ".speed-slider { width: 80%; max-width: 300px; height: 20px; border-radius: 10px; appearance: none; outline: none; background: linear-gradient(to right, yellow, orange, red); }";
  html += ".speed-slider::-webkit-slider-thumb { -webkit-appearance: none; appearance: none; width: 30px; height: 30px; background: white; border-radius: 50%; border: 2px solid #333; cursor: pointer; }";
  html += ".speed-slider::-moz-range-thumb { width: 30px; height: 30px; background: white; border-radius: 50%; border: 2px solid #333; cursor: pointer; }";
  html += ".speed-label { margin-top: 10px; font-size: 18px; color: #555; }";
  html += ".button { margin: 10px; padding: 10px 20px; font-size: 16px; color: white; border: none; border-radius: 5px; cursor: pointer; }";
  html += ".button-off { background-color: #FF4444; }";
  html += ".button-vibration { background-color: #4CAF50; }";
  html += "</style>";
  html += "<title>MuSE</title>";
  html += "</head>";
  html += "<body>";
  html += "<div class=\"container\">";
  
  // Speed Slider Section
  html += "<h2>Speed Modes</h2>";
  html += "<input type=\"range\" min=\"0\" max=\"7\" value=\"" + String(currentManufacturerDataIndex) + "\" class=\"speed-slider\" id=\"speedSlider\" oninput=\"updateSpeedLabel(this.value); updateMode(this.value)\">";
  html += "<p class=\"speed-label\" id=\"speedLabel\">" + String(
      currentManufacturerDataIndex == 0 ? "off" :
      currentManufacturerDataIndex == 1 ? "speed 1" :
      currentManufacturerDataIndex == 2 ? "speed 2" :
      currentManufacturerDataIndex == 3 ? "speed 3" :
      currentManufacturerDataIndex == 4 ? "speed 4" :
      currentManufacturerDataIndex == 5 ? "speed 5" :
      currentManufacturerDataIndex == 6 ? "speed 6" :
      "speed 7"
  ) + "</p>";

  // Vibration Buttons Section
  html += "<h2>Vibration Modes</h2>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(8)\">Vibration 1</button>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(9)\">Vibration 2</button>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(10)\">Vibration 3</button>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(11)\">Vibration 4</button>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(12)\">Vibration 5</button>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(13)\">Vibration 6</button>";
  html += "<button class=\"button button-vibration\" onclick=\"setVibrationMode(14)\">Vibration 7</button>";

  // Off Button
  html += "<button class=\"button button-off\" onclick=\"setVibrationMode(0)\">Off</button>";

  html += "</div>";
  html += "<script>";
  html += "function updateSpeedLabel(value) {";
  html += "  const labels = ['off', 'speed 1', 'speed 2', 'speed 3', 'speed 4', 'speed 5', 'speed 6', 'speed 7'];";
  html += "  document.getElementById('speedLabel').textContent = labels[value];";
  html += "}";
  html += "function updateMode(value) {";
  html += "  fetch('/setMode', {";
  html += "    method: 'POST',";
  html += "    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },";
  html += "    body: 'mode=' + value";
  html += "  });";
  html += "}";
  html += "function setVibrationMode(mode) {";
  html += "  fetch('/setMode', {";
  html += "    method: 'POST',";
  html += "    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },";
  html += "    body: 'mode=' + mode";
  html += "  });";
  html += "}";
  html += "document.getElementById('speedSlider').addEventListener('wheel', function(event) {";
  html += "  event.preventDefault();";
  html += "  let newValue = this.value - (event.deltaY > 0 ? 1 : -1);";
  html += "  if (newValue < 0) newValue = 0;";
  html += "  if (newValue > 7) newValue = 7;";
  html += "  this.value = newValue;";
  html += "  updateSpeedLabel(newValue);";
  html += "  updateMode(newValue);";
  html += "});";
  html += "</script>";
  html += "</body>";
  html += "</html>";

  server.send(200, "text/html", html);
}

void IRAM_ATTR handleSetMode() {
  if (server.hasArg("mode")) {
    uint8_t newMode = server.arg("mode").toInt();
    if (newMode >= 0 && newMode <= 14) { // Check for valid range (0-14)
      currentManufacturerDataIndex = newMode;
      modeChanged = true;
    }
  }
  server.sendHeader("Location", "/");
  server.send(302, "text/plain", "");
}

void handleNotFound() {
  server.send(404, "text/plain", "Not found");
}

void initWebServer() {
  server.on("/", handleRoot);
  server.on("/setMode", HTTP_POST, handleSetMode);
  server.onNotFound(handleNotFound);
  server.begin();
}

void setup() {
  Serial.begin(115200);
  connectWiFi();
  initWebServer();
  NimBLEDevice::init(deviceName);
}

unsigned long previousMillis = 0;
const unsigned long interval = 50; // Interval in milliseconds

void loop() {
  server.handleClient();
  if (modeChanged) {
    modeChanged = false;
    advertiseManufacturerData(currentManufacturerDataIndex);
  }

  unsigned long currentMillis = millis();
  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
  }
}
```

**Comment by interceptor70** [comment]
Hi

Which versions are needed for compiling ?

#include <NimBLEDevice.h>
#include <WiFi.h>
#include <WebServer.h>

Lg Gerrit

**Comment by Ilovemessingwithai** [comment]
Hey @Fi0nee, could you please tell if your code is working as is or are there any extra libraries that need to be installed? It throws me errors. Also, how do you access the web ui? Thank you.

**Comment by Fi0nee** [comment]
Hi @interceptor70 
'''
#include <NimBLEDevice.h> //version 1.4.2 (h2zero)
'''

**Comment by interceptor70** [comment]
Then I have some version conflict, the compiler runs through without error
but I can't connect, the device MuSE_Advertiser doesn't show up anywhere (scan with advanced IP scan)

**Comment by Fi0nee** [comment]
@interceptor70  Just to clarify — are you trying to find the device as a BLE peripheral? The code actually uses Wi-Fi for connection and control. It sets up a web interface that you can access via the ESP32’s IP address once it’s connected to your Wi-Fi network.

**Comment by interceptor70** [comment]
yes it's clear to me, that's why I'm looking for MuSE_Advertiser or a new device in the network in the WLAN, an IP is not assigned.

```
// WiFi Credentials
const char *ssid = "*****";
const char *password = "******************";
```

**Comment by Fi0nee** [comment]
@interceptor70 I updated my code above, added the connection output in monitor port (115200) . You should see the following:

Connecting to WiFi....
WiFi connected.
IP address: 192.168.1.49
Web server started.
Advertising mode: 0
BLE advertising started.

**Comment by Ilovemessingwithai** [comment]
@Fi0nee I'm not sure if I'm doing something wrong, but even after using your updated code and the correct library versions, I'm still encountering these errors:

```
C:\Users\gtfo\Documents\Arduino\muse\muse.ino: In function 'void advertiseManufacturerData(uint8_t)':
C:\Users\gtfo\Documents\Arduino\muse\muse.ino:49:17: error: 'class NimBLEAdvertising' has no member named 'setScanResponse'; did you mean 'setScanResponseData'?
   pAdvertising->setScanResponse(true);
                 ^~~~~~~~~~~~~~~
                 setScanResponseData
C:\Users\gtfo\Documents\Arduino\muse\muse.ino:50:17: error: 'class NimBLEAdvertising' has no member named 'setMaxPreferred'; did you mean 'setMaxInterval'?
   pAdvertising->setMaxPreferred(0x12);
                 ^~~~~~~~~~~~~~~
                 setMaxInterval
C:\Users\gtfo\Documents\Arduino\muse\muse.ino:51:17: error: 'class NimBLEAdvertising' has no member named 'setMinPreferred'; did you mean 'setMinInterval'?
   pAdvertising->setMinPreferred(0x02);
                 ^~~~~~~~~~~~~~~
                 setMinInterval
Multiple libraries were found for "WiFi.h"
  Used: C:\Users\gtfo\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\WiFi
  Not used: C:\Users\gtfo\Documents\Arduino\libraries\WiFiEspAT
exit status 1

Compilation error: 'class NimBLEAdvertising' has no member named 'setScanResponse'; did you mean 'setScanResponseData'?
```

I'm still pretty new to all of this, so it's a bit tough for me to troubleshoot exactly what's going wrong.
Also, will this setup work with any Lovespouse device, or would we need to capture specific manufacturer data for each individual toy if that's possible?

I'm using a NodeMCU ESP32S (Boards Managers: esp32 by Espressif Systems v2.0.17)

**Comment by Fi0nee** [comment]
@Ilovemessingwithai

It looks like you are using a newer version of the NimBLE-Arduino library.
The code I shared was written for version 1.4.2 (by h2zero), where functions like setScanResponse(true), setMaxPreferred(), and setMinPreferred() exist.
In the newer versions, these functions have been changed or removed.
To fix the errors, please install NimBLE-Arduino v1.4.2

My Boards Managers: esp32 v2.0.18 - arduino.5

Should work with any LoveSpouse device.

**Comment by Ilovemessingwithai** [comment]
@Fi0nee Thank you, it compiles and advertises accurately!

**Comment by Fi0nee** [comment]
@Ilovemessingwithai
I was glad to help. I can offer a bundle of esp 32+python to work via COM port. Improved web server design, no freezes

**Comment by Ilovemessingwithai** [comment]
@Fi0nee 
Thanks! Could you tell me a bit more about how it works and what’s included in the bundle?

I’ve also been exploring the idea of making the Lovespouse toy react to games and scripts using Buttplug.io and Intiface—though I’m still super new to all of this and do not know if its possible. The whole teledildonics thing really piqued my interest lately, and I’m just starting to dig in and see what’s possible 😅

**Comment by Fi0nee** [comment]
@Ilovemessingwithai

My project assumed simple control via the web interface, because the Love Spoon application is terribly laggy on my device. My ESP+python bundle works like the code above, only uses python as a web server by sending commands to ESP using the COM port, resulting in no freezes and delays

I haven't really studied Butt much. plug.io and Interface, but I can say for sure that the project is working:
> > create an ESP32 gateway firmware
> 
> I did just that: https://github.com/IngeniousKink/LVS-Gateway:
> 
> ESP32 firmware that poses as a Lovense toy and broadcasts the manufacturer data to MuSE/Love Spouse devices.

I can also assume that using python you can integrate the script with Buttplug.io using the buttplug library.

**Comment by Ilovemessingwithai** [comment]
@Fi0nee 
Oh yes, I totally get the esp32+python idea now. This sounds like a reliable implementation!

**Comment by Fi0nee** [comment]
@Ilovemessingwithai
I created a repository of my ESP+Python project you can use it
[https://github.com/Fi0nee/LoveSpouse_ESP_Python](url)

**Comment by tensiondriven** [comment]
Beautiful, whose working on the Home Assistant integration? :D

**Comment by Aiden-ytarame** [comment]
many thanks, for the people on this thread. ive made a small python script that I use on my laptop to broadcast information by connection to buttplug io via websockets

**Comment by Penta0308** [comment]
I made an android proxy app, to connect LS from Intiface. You don't need special hardware like ESP32. Only an android phone.

https://github.com/Penta0308/LS-Intiface-Bridge

**Comment by Bluscream** [comment]
You can use esphome on a esp32 to have control from your smart home or a web browser

https://github.com/user-attachments/assets/8361dbcf-e058-4eb2-8b55-b7f36c031519

```yaml
esphome:
  name: esphome-esp32-muse
  friendly_name: "MuSE BLE Advertiser"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: '3.1'
    sdkconfig_options:
      CONFIG_BT_ENABLED: "y"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API (optional)
api:

# Enable OTA updates
ota:
  - platform: esphome

# Configure Wi-Fi
wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"

# Initialize ESP32 BLE Stack
esp32_ble:

# ESP32 BLE Server to advertise custom manufacturer data
esp32_ble_server:
  id: ble_server

# Select components for Prefix and Commands
select:
  # Select the prefix for the specific known device
  - platform: template
    name: "BLE Device Prefix"
    id: ble_prefix
    optimistic: true
    options:
      - "wbMSE - 8415 (6D B6 43 CE 97 FE 42 7C)"
      - "wbspy (6D B6 43 F2 53 82 42 7C)"
      - "wb162343 (6D B6 43 AE 99 24 42 7C)"
      - "wb4B9665 (6D B6 43 CA 34 9E 42 7C)"
      - "wb96E533 (6D B6 43 A0 FA 25 42 7C)"
      - "wbEB67C5 (6D B6 43 CF BB 9B 42 7C)"
    initial_option: "wbMSE - 8415 (6D B6 43 CE 97 FE 42 7C)"
    restore_value: true
    on_value:
      then:
        - select.set:
            id: active_command
            option: !lambda "return id(active_command).current_option();"

  # Select the active action to advertise
  - platform: template
    name: "Active BLE Command"
    id: active_command
    optimistic: true
    options:
      - "Stop All Channels"
      - "All Channels Speed 1"
      - "All Channels Speed 2"
      - "All Channels Speed 3"
      - "Stop Channel 1"
      - "Channel 1 Speed 1"
      - "Channel 1 Speed 2"
      - "Channel 1 Speed 3"
      - "Stop Channel 2 / LED Off"
      - "Channel 2 Speed 1 / LED Sky Blue"
      - "Channel 2 Speed 2 / LED Deep Blue"
      - "Channel 2 Speed 3 / LED Dark Green"
      - "LED Light Purple"
      - "LED Light Blue"
      - "LED Orange"
      - "LED Red"
      - "LED Rose Red"
      - "LED Light Green"
      - "Fast Pulse Pattern"
    initial_option: "Stop All Channels"
    on_value:
      then:
        - lambda: |-
            // Company ID: 0xFFF0 (Little Endian: 0xF0, 0xFF)
            uint8_t comp_id[2] = {0xF0, 0xFF};
            std::vector<uint8_t> packet(comp_id, comp_id + 2);
            
            // Map selected BLE prefix option to its corresponding 8-byte array
            std::vector<uint8_t> prefix_bytes;
            if (id(ble_prefix).current_option() == "wbMSE - 8415 (6D B6 43 CE 97 FE 42 7C)") {
              prefix_bytes = {0x6D, 0xB6, 0x43, 0xCE, 0x97, 0xFE, 0x42, 0x7C};
            } else if (id(ble_prefix).current_option() == "wbspy (6D B6 43 F2 53 82 42 7C)") {
              prefix_bytes = {0x6D, 0xB6, 0x43, 0xF2, 0x53, 0x82, 0x42, 0x7C};
            } else if (id(ble_prefix).current_option() == "wb162343 (6D B6 43 AE 99 24 42 7C)") {
              prefix_bytes = {0x6D, 0xB6, 0x43, 0xAE, 0x99, 0x24, 0x42, 0x7C};
            } else if (id(ble_prefix).current_option() == "wb4B9665 (6D B6 43 CA 34 9E 42 7C)") {
              prefix_bytes = {0x6D, 0xB6, 0x43, 0xCA, 0x34, 0x9E, 0x42, 0x7C};
            } else if (id(ble_prefix).current_option() == "wb96E533 (6D B6 43 A0 FA 25 42 7C)") {
              prefix_bytes = {0x6D, 0xB6, 0x43, 0xA0, 0xFA, 0x25, 0x42, 0x7C};
            } else if (id(ble_prefix).current_option() == "wbEB67C5 (6D B6 43 CF BB 9B 42 7C)") {
              prefix_bytes = {0x6D, 0xB6, 0x43, 0xCF, 0xBB, 0x9B, 0x42, 0x7C};
            }

            for (uint8_t b : prefix_bytes) {
              packet.push_back(b);
            }

            if (x == "Stop All Channels") {
              packet.insert(packet.end(), {0xE5, 0x15, 0x7D});
            } else if (x == "All Channels Speed 1") {
              packet.insert(packet.end(), {0xE4, 0x9C, 0x6C});
            } else if (x == "All Channels Speed 2") {
              packet.insert(packet.end(), {0xE7, 0x07, 0x5E});
            } else if (x == "All Channels Speed 3") {
              packet.insert(packet.end(), {0xE6, 0x8E, 0x4F});
            } else if (x == "Stop Channel 1") {
              packet.insert(packet.end(), {0xD5, 0x96, 0x4C});
            } else if (x == "Channel 1 Speed 1") {
              packet.insert(packet.end(), {0xD4, 0x1F, 0x5D});
            } else if (x == "Channel 1 Speed 2") {
              packet.insert(packet.end(), {0xD7, 0x84, 0x6F});
            } else if (x == "Channel 1 Speed 3") {
              packet.insert(packet.end(), {0xD6, 0x0D, 0x7E});
            } else if (x == "Stop Channel 2 / LED Off") {
              packet.insert(packet.end(), {0xA5, 0x11, 0x3F});
            } else if (x == "Channel 2 Speed 1 / LED Sky Blue") {
              packet.insert(packet.end(), {0xA4, 0x98, 0x2E});
            } else if (x == "Channel 2 Speed 2 / LED Deep Blue") {
              packet.insert(packet.end(), {0xA7, 0x03, 0x1C});
            } else if (x == "Channel 2 Speed 3 / LED Dark Green") {
              packet.insert(packet.end(), {0xA6, 0x8A, 0x0D});
            } else if (x == "LED Light Purple") {
              packet.insert(packet.end(), {0xA1, 0x35, 0x79});
            } else if (x == "LED Light Blue") {
              packet.insert(packet.end(), {0xA0, 0xBC, 0x68});
            } else if (x == "LED Orange") {
              packet.insert(packet.end(), {0xA3, 0x27, 0x5A});
            } else if (x == "LED Red") {
              packet.insert(packet.end(), {0xA2, 0xAE, 0x4B});
            } else if (x == "LED Rose Red") {
              packet.insert(packet.end(), {0xAD, 0x59, 0xB3});
            } else if (x == "LED Light Green") {
              packet.insert(packet.end(), {0xAC, 0xD0, 0xA2});
            } else if (x == "Fast Pulse Pattern") {
              packet.insert(packet.end(), {0xE0, 0xB8, 0x2A});
            }

            ESP_LOGD("ble_ad", "Setting BLE Manufacturer Data advertisement");
            id(ble_server).set_manufacturer_data(packet);

button:
  - platform: restart
    id: restart_button
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: template
    name: "Emergency Stop All"
    id: emergency_stop
    on_press:
      then:
        - select.set:
            id: active_command
            option: "Stop All Channels"
```
